### ISSUE TITLE
Provide necessary plumbing to make kubedash work as a tab for Kubernetes UI

### ISSUE THREAD

**Issue by rjnagal** [kubernetes/kubedash#19]
Kubernetes UI provides a mechanism to extend its functionality by defining new tabs dynamically.
Kubedash would be a perfect candidate for such an extension.

We still need to work out he details around authentication and heapster dependency.

**Comment by josephjacks** [comment]
+1

**Comment by preillyme** [comment]
@rjnagal I can take a look this week at added the basics for the tab I think it's a great idea.

**Comment by rjnagal** [comment]
@preillyme That would be awesome!
