### ISSUE TITLE
Update all references to GoogleCloudPlatform

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubedash#21]

**Comment by afein** [comment]
There are no references to GoogleCloudPlatform in Kubedash, other than a reference to kubernetes.

**Comment by vishh** [comment]
https://github.com/kubernetes/kubedash/blob/250aac33d5aae922aac08bba4f06bd139c1c8994/bower.json#L4

https://github.com/kubernetes/kubedash/blob/250aac33d5aae922aac08bba4f06bd139c1c8994/hooks/run_vet.sh#L17

**Comment by afein** [comment]
Apparently I mistyped Google during grep -r ...

Fix incoming.
