### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by apeeyush** [kubernetes/kubedash#32]
Hi,

I could not find setup instructions for setting up kubedash. Could someone pls. add it in the README or comment here and i'll be happy to send a PR.

- Peeyush

**Comment by afein** [comment]
Hi @apeeyush, I have updated the README to include setup and setup instructions.

Heapster v0.18.0 has not been released yet, however. In the meantime, 
feel free to use https://github.com/afein/heapster/tree/model11 

The accuracy of the metrics and the memory consumption of Heapster will be significantly better at the actual v0.18.0 release
