### ISSUE TITLE
Kubernetes logo on kubernetes.io moved

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubedash#61]
404 on the cross-referenced http://kubernetes.io/img/desktop/nav_logo.svg

I think it should be:

http://kubernetes.io/images/nav_logo.svg

![image](https://cloud.githubusercontent.com/assets/1022400/14958807/492c0a38-1041-11e6-9a0c-ab08ff149eb8.png)

**Comment by DazWilkin** [comment]
So, investigating further, the cloned repo does appear to correctly reflect the new logo:

~/pages/index.html

```
<a href="/"><img src="http://kubernetes.io/images/nav_logo.svg" alt="Kubernetes by Google" id="logo-desktop" /></a>
```

However, the README instructs the user to git clone and then e.g.

```
kubectl create -f deploy/bundle.yaml
```

Which I dutifully followed. This uses the existing gcr.io images and, I assume, these aren't built from the same sources as the cloned repo.

I edited the bundle.yaml and replaced the gcr.io image versions with nothing and :latest but neither worked.

**Comment by naphthalene** [comment]
To get the latest version of the code (or if you're playing around with it) you have to build your own image it seems.

If you look in the Makefile:

```
all: build
TAG = v0.2.1                        # Change this
PREFIX = gcr.io/google-containers   # And this
```

You have to change the PREFIX to be a tag that you can build and deploy yourself (using something like https://quay.io)

```
make container
docker push $PREFIX:$TAG
```

Then edit the `deploy/bundle.yaml` to use the new image in:

```
...
      spec:
        containers:
          - image: "$URL/$PREFIX:$TAG"
            name: "kubedash"
...
```

**Comment by DazWilkin** [comment]
Worked. Thanks for the help!

![image](https://cloud.githubusercontent.com/assets/1022400/15263580/4ac287cc-1920-11e6-9d4f-218749bcf1a8.png)

**Comment by moleksyuk** [comment]
For me, it also doesn't display logo correctly, and I followed steps from documentation how to setup dashboard for k8s.

![screen shot 2016-08-11 at 11 10 52](https://cloud.githubusercontent.com/assets/793472/17582438/574e04e6-5fb4-11e6-8f0b-42804a2c4fd2.png)
